import {
  ForeignKeyConstraint,
  TableColumn,
} from "@/lib/databaseSchemaGenerator";

export const schemaDiagramTestTableColumn: TableColumn[] = [
  {
    table_schema: "public",
    table_name: "courses",
    column_name: "course_id",
    data_type: "integer",
    key_type: "PRIMARY KEY",
  },
  {
    table_schema: "public",
    table_name: "courses",
    column_name: "course_name",
    data_type: "character varying",
    key_type: "NONE",
  },
  {
    table_schema: "public",
    table_name: "customers",
    column_name: "customer_id",
    data_type: "integer",
    key_type: "PRIMARY KEY",
  },
  {
    table_schema: "public",
    table_name: "customers",
    column_name: "name",
    data_type: "character varying",
    key_type: "NONE",
  },
  {
    table_schema: "public",
    table_name: "customers",
    column_name: "email",
    data_type: "character varying",
    key_type: "NONE",
  },
  {
    table_schema: "public",
    table_name: "employees",
    column_name: "employee_id",
    data_type: "integer",
    key_type: "PRIMARY KEY",
  },
  {
    table_schema: "public",
    table_name: "employees",
    column_name: "name",
    data_type: "character varying",
    key_type: "NONE",
  },
  {
    table_schema: "public",
    table_name: "employees",
    column_name: "manager_id",
    data_type: "integer",
    key_type: "NONE",
  },
  {
    table_schema: "public",
    table_name: "enrollments",
    column_name: "student_id",
    data_type: "integer",
    key_type: "PRIMARY KEY",
  },
  {
    table_schema: "public",
    table_name: "enrollments",
    column_name: "course_id",
    data_type: "integer",
    key_type: "PRIMARY KEY",
  },
  {
    table_schema: "public",
    table_name: "enrollments",
    column_name: "enrollment_date",
    data_type: "date",
    key_type: "NONE",
  },
  {
    table_schema: "public",
    table_name: "orders",
    column_name: "order_id",
    data_type: "integer",
    key_type: "PRIMARY KEY",
  },
  {
    table_schema: "public",
    table_name: "orders",
    column_name: "customer_id",
    data_type: "integer",
    key_type: "NONE",
  },
  {
    table_schema: "public",
    table_name: "orders",
    column_name: "order_date",
    data_type: "date",
    key_type: "NONE",
  },
  {
    table_schema: "public",
    table_name: "orders",
    column_name: "amount",
    data_type: "numeric",
    key_type: "NONE",
  },
  {
    table_schema: "public",
    table_name: "students",
    column_name: "student_id",
    data_type: "integer",
    key_type: "PRIMARY KEY",
  },
  {
    table_schema: "public",
    table_name: "students",
    column_name: "name",
    data_type: "character varying",
    key_type: "NONE",
  },
  {
    table_schema: "public",
    table_name: "userprofiles",
    column_name: "user_id",
    data_type: "integer",
    key_type: "PRIMARY KEY",
  },
  {
    table_schema: "public",
    table_name: "userprofiles",
    column_name: "bio",
    data_type: "text",
    key_type: "NONE",
  },
  {
    table_schema: "public",
    table_name: "users",
    column_name: "user_id",
    data_type: "integer",
    key_type: "PRIMARY KEY",
  },
  {
    table_schema: "public",
    table_name: "users",
    column_name: "username",
    data_type: "character varying",
    key_type: "NONE",
  },
  {
    table_schema: "public",
    table_name: "users",
    column_name: "email",
    data_type: "character varying",
    key_type: "NONE",
  },
];
export const schemaDiagramTestForeignKeyConstraint: ForeignKeyConstraint[] = [
  {
    constraint_name: "userprofiles_user_id_fkey",
    local_table: "userprofiles",
    local_column: "user_id",
    referenced_table: "users",
    referenced_column: "user_id",
  },
  {
    constraint_name: "orders_customer_id_fkey",
    local_table: "orders",
    local_column: "customer_id",
    referenced_table: "customers",
    referenced_column: "customer_id",
  },
  {
    constraint_name: "enrollments_student_id_fkey",
    local_table: "enrollments",
    local_column: "student_id",
    referenced_table: "students",
    referenced_column: "student_id",
  },
  {
    constraint_name: "enrollments_course_id_fkey",
    local_table: "enrollments",
    local_column: "course_id",
    referenced_table: "courses",
    referenced_column: "course_id",
  },
  {
    constraint_name: "employees_manager_id_fkey",
    local_table: "employees",
    local_column: "manager_id",
    referenced_table: "employees",
    referenced_column: "employee_id",
  },
];
